// 도움말 색인 — 입력 원장(data/commands/input-catalog.json)과 도움말 주제(data/help/topics.json)에서 뽑은 화면용 표.
// 주제 목록 API(계약판 K7-05)가 생기기 전까지 「이 화면」 · 「분류」가 이름을 바로 그리려고 둔다.
// 원장 · 주제와 어긋나면 __tests__/help-index.test.ts 가 빨개진다 — 원장이 바뀌면 이 표를 다시 뽑는다.
// 이름: 원장 displayName, 없으면 주제 제목. 옛 이름은 2026-09-30 승인된 새 이름(help-labels.RENAMED_INPUTS).
import type { InputKind } from './help';

export interface HelpIndexEntry {
    readonly inputId: string;
    readonly kind: InputKind;
    /** 원장 timing.phase */
    readonly phase: string;
    readonly name: string;
}

export const HELP_INDEX: readonly HelpIndexEntry[] = [
    { inputId: 'action.enlist', kind: 'GENERAL_ACTION', phase: 'POLITICS', name: '출사' },
    { inputId: 'action.deploy', kind: 'GENERAL_ACTION', phase: 'MOVE', name: '출병' },
    { inputId: 'action.scout', kind: 'GENERAL_ACTION', phase: 'FIELD', name: '첩보' },
    { inputId: 'action.assault', kind: 'GENERAL_ACTION', phase: 'SIEGE', name: '강공' },
    { inputId: 'action.demandSurrender', kind: 'GENERAL_ACTION', phase: 'SIEGE', name: '항복 권고' },
    { inputId: 'action.siegeRoadFort', kind: 'GENERAL_ACTION', phase: 'SIEGE', name: '보루 포위' },
    { inputId: 'court.dispatch', kind: 'COURT_DECISION', phase: 'DECISION_TURN', name: '발령' },
    { inputId: 'court.dispatchReply', kind: 'COURT_DECISION', phase: 'DECISION_TURN', name: '발령 응답' },
    { inputId: 'court.reward', kind: 'COURT_DECISION', phase: 'DECISION_TURN', name: '상사' },
    { inputId: 'court.politicalConsent', kind: 'COURT_DECISION', phase: 'DECISION_TURN', name: '정치 동의' },
    { inputId: 'placement.assign', kind: 'PLACEMENT', phase: 'NEXT_CARD_TURN', name: '배치' },
    { inputId: 'policy.set', kind: 'POLICY', phase: 'NEXT_CARD_TURN', name: '방침 설정' },
    { inputId: 'work.start', kind: 'WORK', phase: 'NEXT_PHASE_BOUNDARY', name: '공사 시작' },
    { inputId: 'stratagem.rumor', kind: 'STRATAGEM', phase: 'CARD_TRIGGER', name: '유언비어' },
    { inputId: 'stratagem.play', kind: 'STRATAGEM', phase: 'CARD_TRIGGER', name: '계책 사용' },
    { inputId: 'action.farm', kind: 'GENERAL_ACTION', phase: 'FIELD', name: '농지개간' },
    { inputId: 'action.commerce', kind: 'GENERAL_ACTION', phase: 'FIELD', name: '상업투자' },
    { inputId: 'action.fortify', kind: 'GENERAL_ACTION', phase: 'FIELD', name: '수비강화' },
    { inputId: 'action.repairWall', kind: 'GENERAL_ACTION', phase: 'FIELD', name: '성벽보수' },
    { inputId: 'action.security', kind: 'GENERAL_ACTION', phase: 'FIELD', name: '치안강화' },
    { inputId: 'action.settle', kind: 'GENERAL_ACTION', phase: 'FIELD', name: '정착장려' },
    { inputId: 'action.selectResidents', kind: 'GENERAL_ACTION', phase: 'FIELD', name: '주민선정' },
    { inputId: 'action.conscript', kind: 'GENERAL_ACTION', phase: 'FIELD', name: '징병' },
    { inputId: 'action.raiseVolunteers', kind: 'GENERAL_ACTION', phase: 'FIELD', name: '모병' },
    { inputId: 'action.train', kind: 'GENERAL_ACTION', phase: 'FIELD', name: '훈련' },
    { inputId: 'action.boostMorale', kind: 'GENERAL_ACTION', phase: 'FIELD', name: '사기진작' },
    { inputId: 'action.demobilize', kind: 'GENERAL_ACTION', phase: 'FIELD', name: '소집해제' },
    { inputId: 'action.search', kind: 'GENERAL_ACTION', phase: 'FIELD', name: '인재탐색' },
    { inputId: 'action.employ', kind: 'GENERAL_ACTION', phase: 'FIELD', name: '등용' },
    { inputId: 'action.travel', kind: 'GENERAL_ACTION', phase: 'FIELD', name: '견문' },
    { inputId: 'action.selfTrain', kind: 'GENERAL_ACTION', phase: 'FIELD', name: '단련' },
    { inputId: 'action.recuperate', kind: 'GENERAL_ACTION', phase: 'FIELD', name: '요양' },
    { inputId: 'action.gift', kind: 'GENERAL_ACTION', phase: 'FIELD', name: '증여' },
    { inputId: 'action.donate', kind: 'GENERAL_ACTION', phase: 'FIELD', name: '헌납' },
    { inputId: 'action.muster', kind: 'GENERAL_ACTION', phase: 'MOVE', name: '집합' },
    { inputId: 'action.move', kind: 'GENERAL_ACTION', phase: 'MOVE', name: '이동' },
    { inputId: 'action.forcedMarch', kind: 'GENERAL_ACTION', phase: 'MOVE', name: '강행' },
    { inputId: 'action.return', kind: 'GENERAL_ACTION', phase: 'MOVE', name: '귀환' },
    { inputId: 'action.retire', kind: 'GENERAL_ACTION', phase: 'POLITICS', name: '은퇴' },
    { inputId: 'action.resign', kind: 'GENERAL_ACTION', phase: 'POLITICS', name: '하야' },
    { inputId: 'action.rise', kind: 'GENERAL_ACTION', phase: 'POLITICS', name: '거병' },
    { inputId: 'action.foundState', kind: 'GENERAL_ACTION', phase: 'POLITICS', name: '건국' },
    { inputId: 'action.abdicate', kind: 'GENERAL_ACTION', phase: 'POLITICS', name: '선양' },
    { inputId: 'action.dissolve', kind: 'GENERAL_ACTION', phase: 'POLITICS', name: '세력 해산' },
    { inputId: 'action.tour', kind: 'GENERAL_ACTION', phase: 'FIELD', name: '순행' },
    { inputId: 'action.persuadeCaptive', kind: 'GENERAL_ACTION', phase: 'FIELD', name: '포로 설득' },
    { inputId: 'action.oath', kind: 'GENERAL_ACTION', phase: 'POLITICS', name: '결의' },
    { inputId: 'action.independence', kind: 'GENERAL_ACTION', phase: 'POLITICS', name: '독립' },
    { inputId: 'action.convertProficiency', kind: 'GENERAL_ACTION', phase: 'FIELD', name: '병종 바꿔 익히기' },
    { inputId: 'action.tradeEquipment', kind: 'GENERAL_ACTION', phase: 'FIELD', name: '장비매매' },
    { inputId: 'action.tradeGrain', kind: 'GENERAL_ACTION', phase: 'FIELD', name: '쌀 사고팔기' },
    { inputId: 'action.transport', kind: 'GENERAL_ACTION', phase: 'FIELD', name: '물자조달' },
    { inputId: 'court.releaseCorps', kind: 'COURT_DECISION', phase: 'DECISION_TURN', name: '군단 해제' },
    { inputId: 'court.diplomacy', kind: 'COURT_DECISION', phase: 'DECISION_TURN', name: '외교' },
    { inputId: 'court.abandonCounty', kind: 'COURT_DECISION', phase: 'DECISION_TURN', name: '현 포기' },
    { inputId: 'court.institution', kind: 'COURT_DECISION', phase: 'DECISION_TURN', name: '제도 결정' },
    { inputId: 'court.moveCapital', kind: 'COURT_DECISION', phase: 'DECISION_TURN', name: '천도' },
    { inputId: 'court.confiscate', kind: 'COURT_DECISION', phase: 'DECISION_TURN', name: '몰수' },
    { inputId: 'court.nonAggression', kind: 'COURT_DECISION', phase: 'DECISION_TURN', name: '불가침' },
    { inputId: 'court.declareWar', kind: 'COURT_DECISION', phase: 'DECISION_TURN', name: '선전포고' },
    { inputId: 'court.offerPeace', kind: 'COURT_DECISION', phase: 'DECISION_TURN', name: '강화 제안' },
    { inputId: 'court.breakNonAggression', kind: 'COURT_DECISION', phase: 'DECISION_TURN', name: '불가침 파기' },
    { inputId: 'work.reduce', kind: 'WORK', phase: 'NEXT_PHASE_BOUNDARY', name: '공사 감축' },
    { inputId: 'stratagem.steal', kind: 'STRATAGEM', phase: 'CARD_TRIGGER', name: '절도' },
    { inputId: 'stratagem.sabotage', kind: 'STRATAGEM', phase: 'CARD_TRIGGER', name: '파괴공작' },
    { inputId: 'stratagem.fire', kind: 'STRATAGEM', phase: 'CARD_TRIGGER', name: '방화' },
    { inputId: 'stratagem.lastStand', kind: 'STRATAGEM', phase: 'CARD_TRIGGER', name: '배수진' },
    { inputId: 'stratagem.mobilizePeople', kind: 'STRATAGEM', phase: 'CARD_TRIGGER', name: '민심 동원' },
    { inputId: 'stratagem.flood', kind: 'STRATAGEM', phase: 'CARD_TRIGGER', name: '수공' },
    { inputId: 'stratagem.falseReport', kind: 'STRATAGEM', phase: 'CARD_TRIGGER', name: '거짓 보고' },
    { inputId: 'stratagem.raiseMilitia', kind: 'STRATAGEM', phase: 'CARD_TRIGGER', name: '의병 봉기' },
    { inputId: 'stratagem.provokeRivalry', kind: 'STRATAGEM', phase: 'CARD_TRIGGER', name: '이간' },
    { inputId: 'stratagem.raid', kind: 'STRATAGEM', phase: 'CARD_TRIGGER', name: '기습' },
    { inputId: 'stratagem.reciprocity', kind: 'STRATAGEM', phase: 'CARD_TRIGGER', name: '보답' },
];
