CREATE TABLE emperior (
    id            serial PRIMARY KEY,
    phase         text NOT NULL,
    server_id     text NOT NULL,
    nation_count  text NOT NULL,
    nation_name   text NOT NULL,
    nation_hist   text NOT NULL,
    gen_count     text NOT NULL,
    personal_hist text NOT NULL,
    special_hist  text NOT NULL,
    name          text NOT NULL,
    type          text NOT NULL,
    color         text NOT NULL,
    year          integer NOT NULL,
    month         integer NOT NULL,
    power         integer NOT NULL DEFAULT 0,
    gennum        integer NOT NULL DEFAULT 0,
    citynum       integer NOT NULL DEFAULT 0,
    pop           text NOT NULL,
    poprate       text NOT NULL,
    gold          integer NOT NULL DEFAULT 0,
    rice          integer NOT NULL DEFAULT 0,
    l12name       text,
    l12pic        text,
    l11name       text,
    l11pic        text,
    l10name       text,
    l10pic        text,
    l9name        text,
    l9pic         text,
    l8name        text,
    l8pic         text,
    l7name        text,
    l7pic         text,
    l6name        text,
    l6pic         text,
    l5name        text,
    l5pic         text,
    tiger         text NOT NULL DEFAULT '',
    eagle         text NOT NULL DEFAULT '',
    gen           text NOT NULL DEFAULT '',
    history       jsonb NOT NULL DEFAULT '[]'::jsonb,
    aux           jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX emperior_server_idx ON emperior (server_id, id);
