CREATE TABLE IF NOT EXISTS gateway_board_post (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(16) NOT NULL,
    author_account_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    author_name VARCHAR(50) NOT NULL,
    title VARCHAR(120) NOT NULL,
    content_html TEXT NOT NULL,
    pinned BOOLEAN NOT NULL DEFAULT FALSE,
    pinned_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    deleted_by_account_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT gateway_board_post_category_ck CHECK (category IN ('NOTICE', 'FREE', 'SUGGESTION')),
    CONSTRAINT gateway_board_post_pin_state_ck CHECK (
        (pinned = TRUE AND pinned_at IS NOT NULL)
        OR (pinned = FALSE AND pinned_at IS NULL)
    )
);

CREATE INDEX IF NOT EXISTS gateway_board_post_feed_idx
    ON gateway_board_post (pinned DESC, pinned_at DESC, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS gateway_board_post_category_feed_idx
    ON gateway_board_post (category, pinned DESC, pinned_at DESC, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS gateway_board_post_author_account_idx
    ON gateway_board_post (author_account_id);
CREATE INDEX IF NOT EXISTS gateway_board_post_deleted_by_account_idx
    ON gateway_board_post (deleted_by_account_id);

CREATE TABLE IF NOT EXISTS gateway_board_comment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES gateway_board_post(id) ON DELETE CASCADE,
    author_account_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    author_name VARCHAR(50) NOT NULL,
    content_text TEXT NOT NULL,
    deleted_at TIMESTAMPTZ,
    deleted_by_account_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS gateway_board_comment_post_created_idx
    ON gateway_board_comment (post_id, created_at ASC, id ASC);
CREATE INDEX IF NOT EXISTS gateway_board_comment_author_account_idx
    ON gateway_board_comment (author_account_id);
CREATE INDEX IF NOT EXISTS gateway_board_comment_deleted_by_account_idx
    ON gateway_board_comment (deleted_by_account_id);
