-- 게이트웨이 공지(ADR-LITE-049 · 02 로비 우측 「공지」, 01 로그인). 게임 월드가 아니라 계정 층(gateway-api, JPA 쓰기)이 소유한다.
-- 본문은 평문(줄바꿈 유지) — HTML 을 저장하지 않는다.
CREATE TABLE IF NOT EXISTS gateway_notice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(120) NOT NULL,
    body TEXT NOT NULL,
    pinned BOOLEAN NOT NULL DEFAULT FALSE,
    published_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by_account_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS gateway_notice_feed_idx
    ON gateway_notice (pinned DESC, published_at DESC, id DESC)
    WHERE deleted_at IS NULL;
