-- ADR-LITE-049 14 회의실·기밀실: 글 종류(kind)·표결 연결(vote_id)·기밀실 열람 기록(board_post_read).
-- 기존 행은 kind='general'. 열람 기록은 (world_id, post_id, general_id) 멱등 — 첫 열람 시각만 남는다.
-- board_post_read 는 V32 세계 범위 규약을 따른다: world_id 선행 복합 PK · world_state FK · 부모 (world_id, id) 복합 FK ·
-- 모든 인덱스 world_id 선행.
ALTER TABLE board_post ADD COLUMN IF NOT EXISTS kind VARCHAR(16) NOT NULL DEFAULT 'general';
ALTER TABLE board_post ADD COLUMN IF NOT EXISTS vote_id INTEGER;
ALTER TABLE board_post DROP CONSTRAINT IF EXISTS board_post_kind_ck;
ALTER TABLE board_post ADD CONSTRAINT board_post_kind_ck CHECK (kind IN ('general', 'vote', 'operation', 'notice'));

CREATE TABLE IF NOT EXISTS board_post_read (
    world_id    INTEGER NOT NULL,
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    post_id     INTEGER NOT NULL,
    general_id  INTEGER NOT NULL,
    read_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT board_post_read_pkey PRIMARY KEY (world_id, id),
    CONSTRAINT board_post_read_world_id_fkey FOREIGN KEY (world_id) REFERENCES world_state(id),
    CONSTRAINT board_post_read_world_post_fkey FOREIGN KEY (world_id, post_id) REFERENCES board_post(world_id, id) ON DELETE CASCADE,
    CONSTRAINT board_post_read_once_uk UNIQUE (world_id, post_id, general_id)
);
CREATE INDEX IF NOT EXISTS board_post_read_post_idx ON board_post_read (world_id, post_id);
