-- ADR-LITE-049 13 커뮤니티(서버 밖·계정 단위) 확장 — 계정 전역 테이블(세계 범위 아님).
-- 분류 6종(공지·자유·건의·전략/공략·서버 이야기·창작/일지), 조회수, 신고, 계정 대표 장수.
ALTER TABLE gateway_board_post DROP CONSTRAINT IF EXISTS gateway_board_post_category_ck;
ALTER TABLE gateway_board_post
    ADD CONSTRAINT gateway_board_post_category_ck
    CHECK (category IN ('NOTICE', 'FREE', 'SUGGESTION', 'STRATEGY', 'SERVER', 'CREATIVE'));
ALTER TABLE gateway_board_post ADD COLUMN IF NOT EXISTS view_count INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS gateway_board_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT REFERENCES gateway_board_post(id) ON DELETE CASCADE,
    comment_id BIGINT REFERENCES gateway_board_comment(id) ON DELETE CASCADE,
    reporter_account_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    reason VARCHAR(200) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'OPEN',
    handled_by_account_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    handled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT gateway_board_report_status_ck CHECK (status IN ('OPEN', 'HANDLED', 'DISMISSED')),
    -- 글 신고 또는 댓글 신고 중 정확히 하나
    CONSTRAINT gateway_board_report_target_ck CHECK ((post_id IS NULL) <> (comment_id IS NULL))
);
CREATE INDEX IF NOT EXISTS gateway_board_report_status_idx ON gateway_board_report (status, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS gateway_board_report_reporter_idx ON gateway_board_report (reporter_account_id);

-- 계정 대표 장수(커뮤니티 글·댓글 아이콘의 원천). 세계(world_state.id)·장수 id·이름 스냅샷.
ALTER TABLE users ADD COLUMN IF NOT EXISTS representative_world_id INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS representative_general_id INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS representative_general_name VARCHAR(50);
