-- G-01: candidate V75 after actual main V74; no permanent reservation.
-- Production DB approval is required before this draft becomes ready.
CREATE TABLE gateway_board_definition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_key VARCHAR(32) NOT NULL UNIQUE,
    name VARCHAR(80) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    writable BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT gateway_board_definition_key_ck CHECK (board_key ~ '^[A-Z][A-Z0-9_]{0,31}$'),
    CONSTRAINT gateway_board_definition_name_ck CHECK (length(btrim(name)) BETWEEN 1 AND 80)
);
INSERT INTO gateway_board_definition (board_key, name, sort_order) VALUES
    ('NOTICE', '공지', 0), ('FREE', '자유', 1), ('SUGGESTION', '건의', 2),
    ('STRATEGY', '전략·공략', 3), ('SERVER', '서버 이야기', 4), ('CREATIVE', '창작·일지', 5);
ALTER TABLE gateway_board_post ALTER COLUMN category TYPE VARCHAR(32);
ALTER TABLE gateway_board_post DROP CONSTRAINT gateway_board_post_category_ck;
ALTER TABLE gateway_board_post ADD CONSTRAINT gateway_board_post_definition_fk
    FOREIGN KEY (category) REFERENCES gateway_board_definition(board_key) ON DELETE RESTRICT;
CREATE INDEX gateway_board_definition_order_idx ON gateway_board_definition(sort_order, id);
