package opensamguk.infra.persistence

import opensamguk.common.world.WorldId
import opensamguk.logic.inheritance.InheritanceResultRow

fun testFlushPayload(
    worldId: WorldId,
    worldStateUpdate: Map<String, Any?>,
    archiveServerId: String? = null,
    updatedGenerals: List<opensamguk.logic.domain.General> = emptyList(),
    updatedCities: List<opensamguk.logic.domain.City> = emptyList(),
    logEntries: List<LogRow> = emptyList(),
    deletedNationSnapshots: List<Map<String, Any?>> = emptyList(),
    oldGeneralSnapshots: List<OldGeneralArchiveRow> = emptyList(),
    createdGenerals: List<GeneralCreateRow> = emptyList(),
    generalAccessLogUpserts: List<GeneralAccessLogWriteRow> = emptyList(),
    generalAccessLogDeletes: List<Int> = emptyList(),
    updatedNations: List<opensamguk.logic.domain.Nation> = emptyList(),
    createdNations: List<opensamguk.logic.domain.Nation> = emptyList(),
    createdNationTurns: List<opensamguk.logic.domain.NationTurn> = emptyList(),
    createdDiplomacy: List<opensamguk.logic.domain.Diplomacy> = emptyList(),
    updatedDiplomacy: List<DiplomacyUpdate> = emptyList(),
    createdTroops: List<TroopRow> = emptyList(),
    deletedTroops: List<Int> = emptyList(),
    updatedTroops: List<TroopRow> = emptyList(),
    deletedGenerals: List<Int> = emptyList(),
    deletedNations: List<Int> = emptyList(),
    rankWrites: List<RankWrite> = emptyList(),
    rankNationSync: List<RankNationSync> = emptyList(),
    kvWrites: List<KvWrite> = emptyList(),
    createdMessages: List<CreatedMessageRow> = emptyList(),
    messageInvalidates: List<MessageInvalidateRow> = emptyList(),
    diplomacyLetterInserts: List<DiplomacyLetterInsertRow> = emptyList(),
    diplomacyLetterUpdates: LinkedHashMap<Int, LinkedHashMap<String, Any?>> = LinkedHashMap(),
    auctionUpserts: List<AuctionUpsertRow> = emptyList(),
    auctionBidInserts: List<AuctionBidInsertRow> = emptyList(),
    bettingInserts: List<BettingInsertRow> = emptyList(),
    profileIconUpdates: List<ProfileIconUpdateRow> = emptyList(),
    boardPostInserts: List<BoardPostInsertRow> = emptyList(),
    boardCommentInserts: List<BoardCommentInsertRow> = emptyList(),
    votePollInserts: List<VotePollInsertRow> = emptyList(),
    voteInserts: List<VoteInsertRow> = emptyList(),
    voteCommentInserts: List<VoteCommentInsertRow> = emptyList(),
    votePollUpdates: LinkedHashMap<Int, LinkedHashMap<String, Any?>> = LinkedHashMap(),
    inheritanceKvWrites: List<KvWrite> = emptyList(),
    inheritanceLogInserts: List<InheritanceLogRow> = emptyList(),
    inheritanceResultInserts: List<InheritanceResultRow> = emptyList(),
    statisticInserts: List<StatisticInsertRow> = emptyList(),
    yearbookInserts: List<YearbookInsertRow> = emptyList(),
    gameWinnerUpdates: List<GameWinnerUpdateRow> = emptyList(),
    emperiorInserts: List<EmperiorInsertRow> = emptyList(),
    hallUpserts: List<HallUpsertRow> = emptyList(),
    selectPoolMutations: List<SelectPoolMutation> = emptyList(),
    eventInserts: List<EventInsertRow> = emptyList(),
    eventDeletes: List<Int> = emptyList(),
): FlushPayload =
    FlushPayload(
        worldId = worldId,
        worldStateUpdate = worldStateUpdate,
        archiveServerId = archiveServerId,
        updatedGenerals = updatedGenerals,
        updatedCities = updatedCities,
        logEntries = logEntries,
        deletedNationSnapshots = deletedNationSnapshots,
        oldGeneralSnapshots = oldGeneralSnapshots,
        createdGenerals = createdGenerals,
        generalAccessLogUpserts = generalAccessLogUpserts,
        generalAccessLogDeletes = generalAccessLogDeletes,
        updatedNations = updatedNations,
        createdNations = createdNations,
        createdNationTurns = createdNationTurns,
        createdDiplomacy = createdDiplomacy,
        updatedDiplomacy = updatedDiplomacy,
        createdTroops = createdTroops,
        deletedTroops = deletedTroops,
        updatedTroops = updatedTroops,
        deletedGenerals = deletedGenerals,
        deletedNations = deletedNations,
        rankWrites = rankWrites,
        rankNationSync = rankNationSync,
        kvWrites = kvWrites,
        createdMessages = createdMessages,
        messageInvalidates = messageInvalidates,
        diplomacyLetterInserts = diplomacyLetterInserts,
        diplomacyLetterUpdates = diplomacyLetterUpdates,
        auctionUpserts = auctionUpserts,
        auctionBidInserts = auctionBidInserts,
        bettingInserts = bettingInserts,
        profileIconUpdates = profileIconUpdates,
        boardPostInserts = boardPostInserts,
        boardCommentInserts = boardCommentInserts,
        votePollInserts = votePollInserts,
        voteInserts = voteInserts,
        voteCommentInserts = voteCommentInserts,
        votePollUpdates = votePollUpdates,
        inheritanceKvWrites = inheritanceKvWrites,
        inheritanceLogInserts = inheritanceLogInserts,
        inheritanceResultInserts = inheritanceResultInserts,
        statisticInserts = statisticInserts,
        yearbookInserts = yearbookInserts,
        gameWinnerUpdates = gameWinnerUpdates,
        emperiorInserts = emperiorInserts,
        hallUpserts = hallUpserts,
        selectPoolMutations = selectPoolMutations,
        eventInserts = eventInserts,
        eventDeletes = eventDeletes,
    )
