package opensamguk.common.constants

/**
 * GENERATED — `python3 tools/scenario/build_han_world.py` 산출물이다. 손으로 고치지 마라.
 * 고칠 것이 있으면 생성기(GATE_PLACES 별칭 표)를 고치고 다시 돌려라(`--check` 가 드리프트를 잡는다).
 *
 * 'han' 지도 城 id → 그 城이 가진 게이트 키(漢字) 집합 — 州 · 郡 · 治所 縣 · 이민족 거점.
 * han 병종의 ReqRegions(보유 판정) / ForbidRegions(주둔지 판정) 해석에 쓴다.
 * che 는 이 표를 쓰지 않으며(빈 집합), 기존 regionIdByName 경로 그대로 돈다.
 */
object Han780V1GateIndex {
    val keysByCityId: Map<Int, Set<String>> = mapOf(
        1 to setOf("司隸"),
        2 to setOf("司隸"),
        3 to setOf("司隸"),
        4 to setOf("司隸"),
        5 to setOf("司隸"),
        6 to setOf("司隸"),
        7 to setOf("司隸"),
        8 to setOf("司隸"),
        9 to setOf("司隸"),
        10 to setOf("司隸"),
        11 to setOf("司隸"),
        12 to setOf("司隸"),
        13 to setOf("司隸"),
        14 to setOf("司隸"),
        15 to setOf("司隸"),
        16 to setOf("司隸"),
        17 to setOf("司隸"),
        18 to setOf("司隸"),
        19 to setOf("司隸"),
        20 to setOf("司隸"),
        21 to setOf("司隸"),
        22 to setOf("司隸"),
        23 to setOf("司隸"),
        24 to setOf("司隸"),
        25 to setOf("司隸"),
        26 to setOf("司隸"),
        27 to setOf("司隸"),
        28 to setOf("司隸"),
        29 to setOf("司隸"),
        30 to setOf("司隸"),
        31 to setOf("司隸"),
        32 to setOf("司隸"),
        33 to setOf("司隸"),
        34 to setOf("司隸"),
        35 to setOf("司隸"),
        36 to setOf("司隸"),
        37 to setOf("司隸"),
        38 to setOf("司隸"),
        39 to setOf("司隸"),
        40 to setOf("司隸"),
        41 to setOf("司隸"),
        42 to setOf("司隸"),
        43 to setOf("司隸"),
        44 to setOf("司隸"),
        45 to setOf("司隸"),
        46 to setOf("司隸", "雒陽"),
        47 to setOf("司隸", "雒陽"),
        48 to setOf("司隸", "雒陽"),
        49 to setOf("司隸", "雒陽"),
        50 to setOf("司隸", "雒陽"),
        51 to setOf("司隸", "雒陽"),
        52 to setOf("司隸", "雒陽"),
        53 to setOf("司隸", "雒陽"),
        54 to setOf("司隸", "雒陽"),
        55 to setOf("司隸", "雒陽"),
        56 to setOf("司隸", "雒陽"),
        57 to setOf("司隸", "雒陽"),
        58 to setOf("司隸", "雒陽"),
        59 to setOf("司隸", "雒陽"),
        60 to setOf("司隸", "河東"),
        61 to setOf("司隸", "河東"),
        62 to setOf("司隸", "河東"),
        63 to setOf("司隸", "河東"),
        64 to setOf("司隸", "河東"),
        65 to setOf("司隸", "河東"),
        66 to setOf("司隸", "河東"),
        67 to setOf("司隸", "河東"),
        68 to setOf("司隸", "河東"),
        69 to setOf("司隸", "河東"),
        70 to setOf("司隸", "河東"),
        71 to setOf("司隸", "河東"),
        72 to setOf("司隸", "河東"),
        73 to setOf("司隸", "河東"),
        74 to setOf("司隸", "河東"),
        75 to setOf("司隸"),
        76 to setOf("司隸"),
        77 to setOf("豫州"),
        78 to setOf("豫州"),
        79 to setOf("豫州"),
        80 to setOf("豫州"),
        81 to setOf("豫州"),
        82 to setOf("豫州"),
        83 to setOf("豫州"),
        84 to setOf("豫州"),
        85 to setOf("豫州"),
        86 to setOf("豫州"),
        87 to setOf("豫州"),
        88 to setOf("豫州"),
        89 to setOf("豫州"),
        90 to setOf("豫州"),
        91 to setOf("豫州"),
        92 to setOf("豫州"),
        93 to setOf("豫州"),
        94 to setOf("豫州"),
        95 to setOf("豫州"),
        96 to setOf("豫州"),
        97 to setOf("豫州"),
        98 to setOf("豫州"),
        99 to setOf("豫州"),
        100 to setOf("豫州"),
        101 to setOf("豫州"),
        102 to setOf("豫州"),
        103 to setOf("豫州"),
        104 to setOf("豫州"),
        105 to setOf("豫州"),
        106 to setOf("豫州"),
        107 to setOf("豫州"),
        108 to setOf("豫州"),
        109 to setOf("豫州"),
        110 to setOf("豫州"),
        111 to setOf("豫州"),
        112 to setOf("豫州"),
        113 to setOf("豫州"),
        114 to setOf("豫州"),
        115 to setOf("豫州"),
        116 to setOf("豫州"),
        117 to setOf("豫州"),
        118 to setOf("豫州"),
        119 to setOf("豫州"),
        120 to setOf("豫州"),
        121 to setOf("豫州"),
        122 to setOf("豫州"),
        123 to setOf("豫州"),
        124 to setOf("豫州"),
        125 to setOf("豫州"),
        126 to setOf("豫州"),
        127 to setOf("豫州"),
        128 to setOf("豫州"),
        129 to setOf("豫州"),
        130 to setOf("豫州"),
        131 to setOf("豫州"),
        132 to setOf("豫州"),
        133 to setOf("豫州"),
        134 to setOf("豫州"),
        135 to setOf("豫州"),
        136 to setOf("豫州"),
        137 to setOf("豫州"),
        138 to setOf("豫州"),
        139 to setOf("豫州"),
        140 to setOf("豫州"),
        141 to setOf("豫州"),
        142 to setOf("豫州"),
        143 to setOf("豫州"),
        144 to setOf("豫州"),
        145 to setOf("豫州"),
        146 to setOf("豫州"),
        147 to setOf("豫州"),
        148 to setOf("豫州"),
        149 to setOf("豫州"),
        150 to setOf("豫州"),
        151 to setOf("冀州"),
        152 to setOf("冀州"),
        153 to setOf("冀州"),
        154 to setOf("冀州"),
        155 to setOf("冀州"),
        156 to setOf("冀州"),
        157 to setOf("冀州"),
        158 to setOf("冀州"),
        159 to setOf("冀州"),
        160 to setOf("冀州"),
        161 to setOf("冀州"),
        162 to setOf("冀州"),
        163 to setOf("冀州"),
        164 to setOf("冀州"),
        165 to setOf("冀州"),
        166 to setOf("冀州"),
        167 to setOf("冀州"),
        168 to setOf("冀州"),
        169 to setOf("冀州"),
        170 to setOf("冀州"),
        171 to setOf("冀州"),
        172 to setOf("冀州"),
        173 to setOf("冀州"),
        174 to setOf("冀州"),
        175 to setOf("冀州"),
        176 to setOf("冀州"),
        177 to setOf("冀州"),
        178 to setOf("冀州"),
        179 to setOf("冀州"),
        180 to setOf("冀州"),
        181 to setOf("冀州"),
        182 to setOf("冀州"),
        183 to setOf("冀州"),
        184 to setOf("冀州"),
        185 to setOf("冀州"),
        186 to setOf("冀州"),
        187 to setOf("冀州"),
        188 to setOf("冀州"),
        189 to setOf("冀州"),
        190 to setOf("冀州"),
        191 to setOf("冀州"),
        192 to setOf("冀州"),
        193 to setOf("冀州"),
        194 to setOf("冀州"),
        195 to setOf("冀州"),
        196 to setOf("冀州"),
        197 to setOf("冀州"),
        198 to setOf("冀州"),
        199 to setOf("冀州"),
        200 to setOf("冀州"),
        201 to setOf("冀州"),
        202 to setOf("冀州"),
        203 to setOf("冀州"),
        204 to setOf("冀州"),
        205 to setOf("冀州"),
        206 to setOf("冀州"),
        207 to setOf("冀州"),
        208 to setOf("冀州"),
        209 to setOf("冀州"),
        210 to setOf("冀州"),
        211 to setOf("冀州"),
        212 to setOf("冀州"),
        213 to setOf("冀州"),
        214 to setOf("冀州"),
        215 to setOf("冀州"),
        216 to setOf("冀州"),
        217 to setOf("冀州"),
        218 to setOf("冀州"),
        219 to setOf("冀州"),
        220 to setOf("冀州"),
        221 to setOf("冀州"),
        222 to setOf("冀州"),
        223 to setOf("冀州"),
        224 to setOf("冀州"),
        225 to setOf("冀州"),
        226 to setOf("冀州"),
        227 to setOf("冀州"),
        228 to setOf("冀州"),
        229 to setOf("冀州"),
        230 to setOf("冀州"),
        231 to setOf("冀州"),
        232 to setOf("冀州"),
        233 to setOf("冀州"),
        234 to setOf("冀州"),
        235 to setOf("冀州"),
        236 to setOf("冀州"),
        237 to setOf("冀州"),
        238 to setOf("兗州"),
        239 to setOf("兗州"),
        240 to setOf("兗州"),
        241 to setOf("兗州"),
        242 to setOf("兗州"),
        243 to setOf("兗州"),
        244 to setOf("兗州"),
        245 to setOf("兗州"),
        246 to setOf("兗州"),
        247 to setOf("兗州"),
        248 to setOf("兗州"),
        249 to setOf("兗州"),
        250 to setOf("兗州"),
        251 to setOf("兗州"),
        252 to setOf("兗州"),
        253 to setOf("兗州"),
        254 to setOf("兗州"),
        255 to setOf("兗州"),
        256 to setOf("兗州"),
        257 to setOf("兗州"),
        258 to setOf("兗州"),
        259 to setOf("兗州"),
        260 to setOf("兗州"),
        261 to setOf("兗州"),
        262 to setOf("兗州"),
        263 to setOf("兗州"),
        264 to setOf("兗州"),
        265 to setOf("兗州"),
        266 to setOf("兗州"),
        267 to setOf("兗州"),
        268 to setOf("兗州"),
        269 to setOf("兗州"),
        270 to setOf("兗州"),
        271 to setOf("兗州"),
        272 to setOf("兗州"),
        273 to setOf("兗州"),
        274 to setOf("兗州"),
        275 to setOf("兗州"),
        276 to setOf("兗州"),
        277 to setOf("兗州"),
        278 to setOf("兗州"),
        279 to setOf("兗州"),
        280 to setOf("兗州"),
        281 to setOf("兗州"),
        282 to setOf("兗州"),
        283 to setOf("兗州"),
        284 to setOf("兗州"),
        285 to setOf("兗州"),
        286 to setOf("兗州"),
        287 to setOf("兗州"),
        288 to setOf("兗州"),
        289 to setOf("兗州"),
        290 to setOf("兗州"),
        291 to setOf("兗州"),
        292 to setOf("兗州"),
        293 to setOf("兗州"),
        294 to setOf("兗州"),
        295 to setOf("兗州"),
        296 to setOf("兗州"),
        297 to setOf("兗州"),
        298 to setOf("兗州"),
        299 to setOf("徐州"),
        300 to setOf("徐州"),
        301 to setOf("徐州"),
        302 to setOf("徐州"),
        303 to setOf("徐州"),
        304 to setOf("徐州"),
        305 to setOf("徐州"),
        306 to setOf("徐州"),
        307 to setOf("徐州"),
        308 to setOf("徐州"),
        309 to setOf("徐州"),
        310 to setOf("徐州"),
        311 to setOf("徐州"),
        312 to setOf("徐州"),
        313 to setOf("徐州"),
        314 to setOf("徐州"),
        315 to setOf("徐州"),
        316 to setOf("徐州"),
        317 to setOf("徐州"),
        318 to setOf("徐州"),
        319 to setOf("徐州"),
        320 to setOf("徐州"),
        321 to setOf("徐州"),
        322 to setOf("徐州"),
        323 to setOf("徐州"),
        324 to setOf("徐州"),
        325 to setOf("徐州"),
        326 to setOf("徐州"),
        327 to setOf("徐州"),
        328 to setOf("徐州"),
        329 to setOf("徐州"),
        330 to setOf("徐州"),
        331 to setOf("徐州"),
        332 to setOf("徐州"),
        333 to setOf("徐州"),
        334 to setOf("徐州"),
        335 to setOf("徐州"),
        336 to setOf("徐州"),
        337 to setOf("徐州"),
        338 to setOf("徐州"),
        339 to setOf("徐州"),
        340 to setOf("徐州"),
        341 to setOf("徐州"),
        342 to setOf("徐州"),
        343 to setOf("徐州"),
        344 to setOf("徐州"),
        345 to setOf("徐州"),
        346 to setOf("徐州"),
        347 to setOf("青州"),
        348 to setOf("青州"),
        349 to setOf("青州"),
        350 to setOf("青州"),
        351 to setOf("青州"),
        352 to setOf("青州"),
        353 to setOf("青州"),
        354 to setOf("青州"),
        355 to setOf("青州"),
        356 to setOf("青州"),
        357 to setOf("青州"),
        358 to setOf("青州"),
        359 to setOf("青州"),
        360 to setOf("青州"),
        361 to setOf("青州"),
        362 to setOf("青州"),
        363 to setOf("青州"),
        364 to setOf("青州"),
        365 to setOf("青州"),
        366 to setOf("青州"),
        367 to setOf("青州"),
        368 to setOf("青州"),
        369 to setOf("青州"),
        370 to setOf("青州"),
        371 to setOf("青州"),
        372 to setOf("青州"),
        373 to setOf("青州"),
        374 to setOf("青州"),
        375 to setOf("青州"),
        376 to setOf("青州"),
        377 to setOf("青州"),
        378 to setOf("青州"),
        379 to setOf("青州"),
        380 to setOf("青州"),
        381 to setOf("青州"),
        382 to setOf("青州"),
        383 to setOf("青州"),
        384 to setOf("青州"),
        385 to setOf("青州"),
        386 to setOf("青州"),
        387 to setOf("青州"),
        388 to setOf("青州"),
        389 to setOf("青州"),
        390 to setOf("青州"),
        391 to setOf("青州"),
        392 to setOf("青州"),
        393 to setOf("青州"),
        394 to setOf("青州"),
        395 to setOf("青州"),
        396 to setOf("青州"),
        397 to setOf("秭歸", "荊州"),
        398 to setOf("秭歸", "荊州"),
        399 to setOf("秭歸", "荊州"),
        400 to setOf("秭歸", "荊州"),
        401 to setOf("秭歸", "荊州"),
        402 to setOf("秭歸", "荊州"),
        403 to setOf("秭歸", "荊州"),
        404 to setOf("秭歸", "荊州"),
        405 to setOf("秭歸", "荊州"),
        406 to setOf("秭歸", "荊州"),
        407 to setOf("秭歸", "荊州"),
        408 to setOf("秭歸", "荊州"),
        409 to setOf("秭歸", "荊州"),
        410 to setOf("秭歸", "荊州"),
        411 to setOf("荊州"),
        412 to setOf("荊州"),
        413 to setOf("荊州"),
        414 to setOf("荊州"),
        415 to setOf("荊州"),
        416 to setOf("荊州"),
        417 to setOf("荊州"),
        418 to setOf("荊州"),
        419 to setOf("荊州"),
        420 to setOf("荊州"),
        421 to setOf("荊州"),
        422 to setOf("荊州"),
        423 to setOf("荊州"),
        424 to setOf("荊州"),
        425 to setOf("荊州"),
        426 to setOf("荊州"),
        427 to setOf("荊州"),
        428 to setOf("荊州"),
        429 to setOf("荊州"),
        430 to setOf("荊州"),
        431 to setOf("荊州"),
        432 to setOf("荊州"),
        433 to setOf("荊州"),
        434 to setOf("荊州"),
        435 to setOf("荊州"),
        436 to setOf("荊州"),
        437 to setOf("荊州"),
        438 to setOf("荊州"),
        439 to setOf("荊州"),
        440 to setOf("荊州"),
        441 to setOf("荊州"),
        442 to setOf("荊州"),
        443 to setOf("荊州"),
        444 to setOf("荊州"),
        445 to setOf("荊州"),
        446 to setOf("荊州"),
        447 to setOf("荊州"),
        448 to setOf("荊州"),
        449 to setOf("荊州"),
        450 to setOf("荊州"),
        451 to setOf("荊州"),
        452 to setOf("荊州"),
        453 to setOf("荊州"),
        454 to setOf("荊州"),
        455 to setOf("荊州"),
        456 to setOf("荊州"),
        457 to setOf("荊州"),
        458 to setOf("荊州"),
        459 to setOf("荊州"),
        460 to setOf("荊州"),
        461 to setOf("荊州"),
        462 to setOf("荊州"),
        463 to setOf("荊州"),
        464 to setOf("荊州"),
        465 to setOf("荊州"),
        466 to setOf("荊州"),
        467 to setOf("荊州"),
        468 to setOf("荊州"),
        469 to setOf("荊州"),
        470 to setOf("荊州"),
        471 to setOf("荊州"),
        472 to setOf("荊州"),
        473 to setOf("荊州"),
        474 to setOf("荊州"),
        475 to setOf("荊州"),
        476 to setOf("荊州"),
        477 to setOf("荊州"),
        478 to setOf("荊州"),
        479 to setOf("荊州"),
        480 to setOf("荊州"),
        481 to setOf("荊州"),
        482 to setOf("荊州"),
        483 to setOf("荊州"),
        484 to setOf("荊州"),
        485 to setOf("荊州"),
        486 to setOf("荊州"),
        487 to setOf("荊州"),
        488 to setOf("荊州"),
        489 to setOf("荊州"),
        490 to setOf("荊州"),
        491 to setOf("荊州"),
        492 to setOf("荊州"),
        493 to setOf("荊州"),
        494 to setOf("荊州"),
        495 to setOf("荊州"),
        496 to setOf("荊州"),
        497 to setOf("荊州"),
        498 to setOf("荊州"),
        499 to setOf("丹楊", "揚州"),
        500 to setOf("丹楊", "揚州"),
        501 to setOf("丹楊", "揚州"),
        502 to setOf("丹楊", "揚州"),
        503 to setOf("丹楊", "揚州"),
        504 to setOf("丹楊", "揚州"),
        505 to setOf("丹楊", "揚州"),
        506 to setOf("丹楊", "揚州"),
        507 to setOf("丹楊", "揚州"),
        508 to setOf("丹楊", "揚州"),
        509 to setOf("丹楊", "揚州"),
        510 to setOf("丹楊", "揚州"),
        511 to setOf("丹楊", "揚州"),
        512 to setOf("丹楊", "揚州"),
        513 to setOf("揚州"),
        514 to setOf("揚州"),
        515 to setOf("揚州"),
        516 to setOf("揚州"),
        517 to setOf("揚州"),
        518 to setOf("揚州"),
        519 to setOf("揚州"),
        520 to setOf("揚州"),
        521 to setOf("揚州"),
        522 to setOf("揚州"),
        523 to setOf("揚州"),
        524 to setOf("山越", "揚州"),
        525 to setOf("揚州"),
        526 to setOf("揚州"),
        527 to setOf("揚州"),
        528 to setOf("揚州"),
        529 to setOf("揚州"),
        530 to setOf("揚州"),
        531 to setOf("揚州"),
        532 to setOf("揚州"),
        533 to setOf("揚州"),
        534 to setOf("揚州"),
        535 to setOf("揚州"),
        536 to setOf("揚州"),
        537 to setOf("揚州"),
        538 to setOf("揚州"),
        539 to setOf("揚州"),
        540 to setOf("揚州"),
        541 to setOf("揚州"),
        542 to setOf("揚州"),
        543 to setOf("揚州"),
        544 to setOf("揚州"),
        545 to setOf("揚州"),
        546 to setOf("揚州"),
        547 to setOf("揚州"),
        548 to setOf("揚州"),
        549 to setOf("揚州"),
        550 to setOf("揚州"),
        551 to setOf("揚州"),
        552 to setOf("揚州"),
        553 to setOf("揚州"),
        554 to setOf("揚州"),
        555 to setOf("揚州"),
        556 to setOf("揚州"),
        557 to setOf("揚州"),
        558 to setOf("揚州"),
        559 to setOf("揚州"),
        560 to setOf("揚州"),
        561 to setOf("揚州"),
        562 to setOf("揚州"),
        563 to setOf("揚州"),
        564 to setOf("揚州"),
        565 to setOf("揚州"),
        566 to setOf("揚州"),
        567 to setOf("揚州"),
        568 to setOf("揚州"),
        569 to setOf("南中", "益州", "蠻"),
        570 to setOf("巴", "益州", "賨"),
        571 to setOf("巴", "巴西", "益州"),
        572 to setOf("巴", "益州", "賨"),
        573 to setOf("巴", "益州", "賨"),
        574 to setOf("巴", "益州", "賨"),
        575 to setOf("巴", "益州", "賨"),
        576 to setOf("巴", "益州", "賨"),
        577 to setOf("巴", "益州", "賨"),
        578 to setOf("巴", "益州", "賨"),
        579 to setOf("巴", "益州", "賨"),
        580 to setOf("巴", "益州", "賨"),
        581 to setOf("益州"),
        582 to setOf("益州"),
        583 to setOf("益州"),
        584 to setOf("益州"),
        585 to setOf("益州"),
        586 to setOf("益州"),
        587 to setOf("益州"),
        588 to setOf("南中", "叟", "益州"),
        589 to setOf("南中", "叟", "益州"),
        590 to setOf("益州"),
        591 to setOf("益州"),
        592 to setOf("益州"),
        593 to setOf("漢中", "益州"),
        594 to setOf("漢中", "益州"),
        595 to setOf("漢中", "益州"),
        596 to setOf("漢中", "益州"),
        597 to setOf("漢中", "益州"),
        598 to setOf("漢中", "益州"),
        599 to setOf("漢中", "益州"),
        600 to setOf("漢中", "益州"),
        601 to setOf("南中", "益州"),
        602 to setOf("南中", "益州"),
        603 to setOf("南中", "益州"),
        604 to setOf("南中", "益州"),
        605 to setOf("南中", "益州"),
        606 to setOf("南中", "益州"),
        607 to setOf("益州"),
        608 to setOf("益州"),
        609 to setOf("益州"),
        610 to setOf("益州"),
        611 to setOf("益州"),
        612 to setOf("南中", "叟", "益州"),
        613 to setOf("益州"),
        614 to setOf("益州"),
        615 to setOf("益州"),
        616 to setOf("益州"),
        617 to setOf("益州"),
        618 to setOf("益州"),
        619 to setOf("益州"),
        620 to setOf("益州"),
        621 to setOf("益州"),
        622 to setOf("益州"),
        623 to setOf("南中", "叟", "益州", "青羌"),
        624 to setOf("南中", "叟", "益州", "青羌"),
        625 to setOf("南中", "叟", "益州", "青羌"),
        626 to setOf("南中", "叟", "益州", "青羌"),
        627 to setOf("涼州"),
        628 to setOf("涼州"),
        629 to setOf("涼州"),
        630 to setOf("涼州"),
        631 to setOf("涼州"),
        632 to setOf("涼州"),
        633 to setOf("涼州"),
        634 to setOf("涼州"),
        635 to setOf("涼州"),
        636 to setOf("涼州"),
        637 to setOf("涼州"),
        638 to setOf("涼州"),
        639 to setOf("涼州"),
        640 to setOf("涼州"),
        641 to setOf("涼州"),
        642 to setOf("涼州"),
        643 to setOf("涼州"),
        644 to setOf("涼州"),
        645 to setOf("涼州"),
        646 to setOf("涼州"),
        647 to setOf("涼州"),
        648 to setOf("涼州"),
        649 to setOf("涼州"),
        650 to setOf("涼州"),
        651 to setOf("涼州"),
        652 to setOf("涼州"),
        653 to setOf("涼州", "羌"),
        654 to setOf("涼州"),
        655 to setOf("涼州", "胡"),
        656 to setOf("涼州", "胡"),
        657 to setOf("涼州", "胡"),
        658 to setOf("涼州", "胡"),
        659 to setOf("涼州", "胡"),
        660 to setOf("涼州"),
        661 to setOf("涼州"),
        662 to setOf("涼州"),
        663 to setOf("涼州"),
        664 to setOf("涼州"),
        665 to setOf("涼州"),
        666 to setOf("涼州"),
        667 to setOf("并州"),
        668 to setOf("并州"),
        669 to setOf("并州"),
        670 to setOf("并州"),
        671 to setOf("并州"),
        672 to setOf("并州"),
        673 to setOf("并州"),
        674 to setOf("并州"),
        675 to setOf("并州"),
        676 to setOf("并州"),
        677 to setOf("并州"),
        678 to setOf("并州"),
        679 to setOf("并州"),
        680 to setOf("并州"),
        681 to setOf("匈奴", "屠各", "并州"),
        682 to setOf("并州"),
        683 to setOf("并州"),
        684 to setOf("并州"),
        685 to setOf("并州"),
        686 to setOf("并州"),
        687 to setOf("并州"),
        688 to setOf("并州"),
        689 to setOf("并州"),
        690 to setOf("并州"),
        691 to setOf("并州"),
        692 to setOf("并州"),
        693 to setOf("并州"),
        694 to setOf("并州"),
        695 to setOf("并州"),
        696 to setOf("并州"),
        697 to setOf("屠各", "并州"),
        698 to setOf("并州"),
        699 to setOf("并州"),
        700 to setOf("并州"),
        701 to setOf("并州"),
        702 to setOf("并州"),
        703 to setOf("并州"),
        704 to setOf("并州"),
        705 to setOf("幽州"),
        706 to setOf("幽州"),
        707 to setOf("幽州"),
        708 to setOf("幽州"),
        709 to setOf("幽州"),
        710 to setOf("幽州"),
        711 to setOf("幽州"),
        712 to setOf("幽州"),
        713 to setOf("幽州"),
        714 to setOf("幽州"),
        715 to setOf("幽州"),
        716 to setOf("幽州"),
        717 to setOf("幽州"),
        718 to setOf("幽州"),
        719 to setOf("幽州"),
        720 to setOf("幽州"),
        721 to setOf("幽州"),
        722 to setOf("幽州"),
        723 to setOf("幽州"),
        724 to setOf("幽州"),
        725 to setOf("幽州"),
        726 to setOf("幽州"),
        727 to setOf("幽州", "烏丸", "烏桓"),
        728 to setOf("幽州"),
        729 to setOf("幽州"),
        730 to setOf("幽州"),
        731 to setOf("幽州"),
        732 to setOf("幽州"),
        733 to setOf("幽州"),
        734 to setOf("幽州", "鮮卑"),
        735 to setOf("交州"),
        736 to setOf("交州"),
        737 to setOf("交州"),
        738 to setOf("交州"),
        739 to setOf("交州"),
        740 to setOf("交州"),
        741 to setOf("交州"),
        742 to setOf("交州"),
        743 to setOf("交州"),
        744 to setOf("交州"),
        745 to setOf("交州", "日南"),
        746 to setOf("交州"),
        747 to setOf("交州"),
        748 to setOf("交州"),
        749 to setOf("交州"),
        750 to setOf("交州"),
        751 to setOf("交州"),
        752 to setOf("交州"),
        753 to setOf("交州"),
        754 to setOf("交州"),
        755 to setOf("交州"),
        756 to setOf("交州"),
        757 to setOf("交州"),
        758 to setOf("交州"),
        760 to setOf("馬韓"),
        761 to setOf("挹婁", "沃沮"),
        762 to setOf("高句麗"),
        763 to setOf("弁韓"),
        764 to setOf("弁韓"),
        765 to setOf("辰韓"),
        766 to setOf("高句麗"),
        767 to setOf("弁韓"),
        768 to setOf("夫餘"),
        769 to setOf("弁韓"),
        771 to setOf("辰韓"),
        772 to setOf("辰韓"),
        773 to setOf("辰韓"),
        774 to setOf("弁韓"),
        775 to setOf("沃沮"),
        776 to setOf("濊"),
        777 to setOf("弁韓"),
        778 to setOf("馬韓"),
        779 to setOf("馬韓"),
        780 to setOf("奴國", "邪馬壹國"),
    )

    fun keys(cityId: Int): Set<String> = keysByCityId[cityId].orEmpty()
}
