package com.opensam.dto

import com.opensam.entity.*
import java.time.OffsetDateTime

data class GeneralResponse(
    val id: Long,
    val worldId: Long,
    val userId: Long?,
    val name: String,
    val nationId: Long,
    val cityId: Long,
    val troopId: Long,
    val npcState: Short,
    val affinity: Short,
    val bornYear: Short,
    val deadYear: Short,
    val picture: String,
    val imageServer: Short,
    val leadership: Short,
    val leadershipExp: Short,
    val strength: Short,
    val strengthExp: Short,
    val intel: Short,
    val intelExp: Short,
    val politics: Short,
    val charm: Short,
    val injury: Short,
    val experience: Int,
    val dedication: Int,
    val officerLevel: Short,
    val officerCity: Int,
    val permission: String,
    val gold: Int,
    val rice: Int,
    val crew: Int,
    val crewType: Short,
    val train: Short,
    val atmos: Short,
    val weaponCode: String,
    val bookCode: String,
    val horseCode: String,
    val itemCode: String,
    val turnTime: OffsetDateTime,
    val recentWarTime: OffsetDateTime?,
    val makeLimit: Short,
    val killTurn: Short?,
    val blockState: Short,
    val dedLevel: Short,
    val expLevel: Short,
    val age: Short,
    val startAge: Short,
    val belong: Short,
    val betray: Short,
    val personalCode: String,
    val specialCode: String,
    val specAge: Short,
    val special2Code: String,
    val spec2Age: Short,
    val defenceTrain: Short,
    val tournamentState: Short,
    val commandPoints: Int,
    val commandEndTime: OffsetDateTime?,
    val lastTurn: Map<String, Any>,
    val meta: Map<String, Any>,
    val penalty: Map<String, Any>,
    val createdAt: OffsetDateTime,
    val updatedAt: OffsetDateTime,
) {
    companion object {
        fun from(e: General) = GeneralResponse(
            id = e.id,
            worldId = e.worldId,
            userId = e.userId,
            name = e.name,
            nationId = e.nationId,
            cityId = e.cityId,
            troopId = e.troopId,
            npcState = e.npcState,
            affinity = e.affinity,
            bornYear = e.bornYear,
            deadYear = e.deadYear,
            picture = e.picture,
            imageServer = e.imageServer,
            leadership = e.leadership,
            leadershipExp = e.leadershipExp,
            strength = e.strength,
            strengthExp = e.strengthExp,
            intel = e.intel,
            intelExp = e.intelExp,
            politics = e.politics,
            charm = e.charm,
            injury = e.injury,
            experience = e.experience,
            dedication = e.dedication,
            officerLevel = e.officerLevel,
            officerCity = e.officerCity,
            permission = e.permission,
            gold = e.gold,
            rice = e.rice,
            crew = e.crew,
            crewType = e.crewType,
            train = e.train,
            atmos = e.atmos,
            weaponCode = e.weaponCode,
            bookCode = e.bookCode,
            horseCode = e.horseCode,
            itemCode = e.itemCode,
            turnTime = e.turnTime,
            recentWarTime = e.recentWarTime,
            makeLimit = e.makeLimit,
            killTurn = e.killTurn,
            blockState = e.blockState,
            dedLevel = e.dedLevel,
            expLevel = e.expLevel,
            age = e.age,
            startAge = e.startAge,
            belong = e.belong,
            betray = e.betray,
            personalCode = e.personalCode,
            specialCode = e.specialCode,
            specAge = e.specAge,
            special2Code = e.special2Code,
            spec2Age = e.spec2Age,
            defenceTrain = e.defenceTrain,
            tournamentState = e.tournamentState,
            commandPoints = e.commandPoints,
            commandEndTime = e.commandEndTime,
            lastTurn = e.lastTurn,
            meta = e.meta,
            penalty = e.penalty,
            createdAt = e.createdAt,
            updatedAt = e.updatedAt,
        )
    }
}

data class NationResponse(
    val id: Long,
    val worldId: Long,
    val name: String,
    val color: String,
    val capitalCityId: Long?,
    val gold: Int,
    val rice: Int,
    val bill: Short,
    val rate: Short,
    val rateTmp: Short,
    val secretLimit: Short,
    val chiefGeneralId: Long,
    val scoutLevel: Short,
    val warState: Short,
    val strategicCmdLimit: Short,
    val surrenderLimit: Short,
    val tech: Float,
    val power: Int,
    val level: Short,
    val typeCode: String,
    val spy: Map<String, Any>,
    val meta: Map<String, Any>,
    val createdAt: OffsetDateTime,
    val updatedAt: OffsetDateTime,
) {
    companion object {
        fun from(e: Nation) = NationResponse(
            id = e.id,
            worldId = e.worldId,
            name = e.name,
            color = e.color,
            capitalCityId = e.capitalCityId,
            gold = e.gold,
            rice = e.rice,
            bill = e.bill,
            rate = e.rate,
            rateTmp = e.rateTmp,
            secretLimit = e.secretLimit,
            chiefGeneralId = e.chiefGeneralId,
            scoutLevel = e.scoutLevel,
            warState = e.warState,
            strategicCmdLimit = e.strategicCmdLimit,
            surrenderLimit = e.surrenderLimit,
            tech = e.tech,
            power = e.power,
            level = e.level,
            typeCode = e.typeCode,
            spy = e.spy,
            meta = e.meta,
            createdAt = e.createdAt,
            updatedAt = e.updatedAt,
        )
    }
}

data class CityResponse(
    val id: Long,
    val worldId: Long,
    val name: String,
    val level: Short,
    val nationId: Long,
    val supplyState: Short,
    val frontState: Short,
    val pop: Int,
    val popMax: Int,
    val agri: Int,
    val agriMax: Int,
    val comm: Int,
    val commMax: Int,
    val secu: Int,
    val secuMax: Int,
    val trust: Float,
    val trade: Int,
    val dead: Int,
    val def: Int,
    val defMax: Int,
    val wall: Int,
    val wallMax: Int,
    val officerSet: Int,
    val state: Short,
    val region: Short,
    val term: Short,
    val conflict: Map<String, Any>,
    val meta: Map<String, Any>,
) {
    companion object {
        fun from(e: City) = CityResponse(
            id = e.id,
            worldId = e.worldId,
            name = e.name,
            level = e.level,
            nationId = e.nationId,
            supplyState = e.supplyState,
            frontState = e.frontState,
            pop = e.pop,
            popMax = e.popMax,
            agri = e.agri,
            agriMax = e.agriMax,
            comm = e.comm,
            commMax = e.commMax,
            secu = e.secu,
            secuMax = e.secuMax,
            trust = e.trust,
            trade = e.trade,
            dead = e.dead,
            def = e.def,
            defMax = e.defMax,
            wall = e.wall,
            wallMax = e.wallMax,
            officerSet = e.officerSet,
            state = e.state,
            region = e.region,
            term = e.term,
            conflict = e.conflict,
            meta = e.meta,
        )
    }
}

data class WorldStateResponse(
    val id: Short,
    val name: String,
    val scenarioCode: String,
    val currentYear: Short,
    val currentMonth: Short,
    val tickSeconds: Int,
    val realtimeMode: Boolean,
    val commandPointRegenRate: Int,
    val config: Map<String, Any>,
    val meta: Map<String, Any>,
    val updatedAt: OffsetDateTime,
) {
    companion object {
        fun from(e: WorldState) = WorldStateResponse(
            id = e.id,
            name = e.name,
            scenarioCode = e.scenarioCode,
            currentYear = e.currentYear,
            currentMonth = e.currentMonth,
            tickSeconds = e.tickSeconds,
            realtimeMode = e.realtimeMode,
            commandPointRegenRate = e.commandPointRegenRate,
            config = e.config,
            meta = e.meta,
            updatedAt = e.updatedAt,
        )
    }
}

data class TroopResponse(
    val id: Long,
    val worldId: Long,
    val leaderGeneralId: Long,
    val nationId: Long,
    val name: String,
    val meta: Map<String, Any>,
    val createdAt: OffsetDateTime,
) {
    companion object {
        fun from(e: Troop) = TroopResponse(
            id = e.id,
            worldId = e.worldId,
            leaderGeneralId = e.leaderGeneralId,
            nationId = e.nationId,
            name = e.name,
            meta = e.meta,
            createdAt = e.createdAt,
        )
    }
}

data class MessageResponse(
    val id: Long,
    val worldId: Long,
    val mailboxCode: String,
    val messageType: String,
    val srcId: Long?,
    val destId: Long?,
    val sentAt: OffsetDateTime,
    val validUntil: OffsetDateTime?,
    val payload: Map<String, Any>,
    val meta: Map<String, Any>,
) {
    companion object {
        fun from(e: Message) = MessageResponse(
            id = e.id,
            worldId = e.worldId,
            mailboxCode = e.mailboxCode,
            messageType = e.messageType,
            srcId = e.srcId,
            destId = e.destId,
            sentAt = e.sentAt,
            validUntil = e.validUntil,
            payload = e.payload,
            meta = e.meta,
        )
    }
}
