spring:
  application:
    name: gateway-api
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
server:
  port: ${GATEWAY_API_PORT:8080}
management:
  endpoints:
    web:
      exposure:
        include: health,info
