package com.opensam.engine.turn.cqrs.memory

import java.time.OffsetDateTime

data class InMemoryWorldState(
    val worldId: Long,
    val generals: MutableMap<Long, GeneralSnapshot> = mutableMapOf(),
    val cities: MutableMap<Long, CitySnapshot> = mutableMapOf(),
    val nations: MutableMap<Long, NationSnapshot> = mutableMapOf(),
    val troops: MutableMap<Long, TroopSnapshot> = mutableMapOf(),
    val diplomacies: MutableMap<Long, DiplomacySnapshot> = mutableMapOf(),
    val generalTurnsByGeneralId: MutableMap<Long, MutableList<GeneralTurnSnapshot>> = mutableMapOf(),
    val nationTurnsByNationAndLevel: MutableMap<NationTurnKey, MutableList<NationTurnSnapshot>> = mutableMapOf(),
)

data class NationTurnKey(
    val nationId: Long,
    val officerLevel: Short,
)

data class GeneralSnapshot(
    val id: Long,
    val worldId: Long,
    val userId: Long?,
    val name: String,
    var nationId: Long,
    var cityId: Long,
    var troopId: Long,
    var npcState: Short,
    var npcOrg: Long?,
    var affinity: Short,
    var bornYear: Short,
    var deadYear: Short,
    var picture: String,
    var imageServer: Short,
    var leadership: Short,
    var leadershipExp: Short,
    var strength: Short,
    var strengthExp: Short,
    var intel: Short,
    var intelExp: Short,
    var politics: Short,
    var charm: Short,
    var dex1: Int,
    var dex2: Int,
    var dex3: Int,
    var dex4: Int,
    var dex5: Int,
    var injury: Short,
    var experience: Int,
    var dedication: Int,
    var officerLevel: Short,
    var officerCity: Int,
    var permission: String,
    var gold: Int,
    var rice: Int,
    var crew: Int,
    var crewType: Short,
    var train: Short,
    var atmos: Short,
    var weaponCode: String,
    var bookCode: String,
    var horseCode: String,
    var itemCode: String,
    var ownerName: String,
    var newmsg: Short,
    var turnTime: OffsetDateTime,
    var recentWarTime: OffsetDateTime?,
    var makeLimit: Short,
    var killTurn: Short?,
    var blockState: Short,
    var dedLevel: Short,
    var expLevel: Short,
    var age: Short,
    var startAge: Short,
    var belong: Short,
    var betray: Short,
    var personalCode: String,
    var specialCode: String,
    var specAge: Short,
    var special2Code: String,
    var spec2Age: Short,
    var defenceTrain: Short,
    var tournamentState: Short,
    var commandPoints: Int,
    var commandEndTime: OffsetDateTime?,
    var lastTurn: MutableMap<String, Any>,
    var meta: MutableMap<String, Any>,
    var penalty: MutableMap<String, Any>,
    var createdAt: OffsetDateTime,
    var updatedAt: OffsetDateTime,
)

data class CitySnapshot(
    val id: Long,
    val worldId: Long,
    val name: String,
    var level: Short,
    var nationId: Long,
    var supplyState: Short,
    var frontState: Short,
    var pop: Int,
    var popMax: Int,
    var agri: Int,
    var agriMax: Int,
    var comm: Int,
    var commMax: Int,
    var secu: Int,
    var secuMax: Int,
    var trust: Float,
    var trade: Int,
    var dead: Int,
    var def: Int,
    var defMax: Int,
    var wall: Int,
    var wallMax: Int,
    var officerSet: Int,
    var state: Short,
    var region: Short,
    var term: Short,
    var conflict: MutableMap<String, Any>,
    var meta: MutableMap<String, Any>,
)

data class NationSnapshot(
    val id: Long,
    val worldId: Long,
    var name: String,
    var color: String,
    var capitalCityId: Long?,
    var gold: Int,
    var rice: Int,
    var bill: Short,
    var rate: Short,
    var rateTmp: Short,
    var secretLimit: Short,
    var chiefGeneralId: Long,
    var scoutLevel: Short,
    var warState: Short,
    var strategicCmdLimit: Short,
    var surrenderLimit: Short,
    var tech: Float,
    var power: Int,
    var level: Short,
    var typeCode: String,
    var spy: MutableMap<String, Any>,
    var meta: MutableMap<String, Any>,
    var createdAt: OffsetDateTime,
    var updatedAt: OffsetDateTime,
)

data class TroopSnapshot(
    val id: Long,
    val worldId: Long,
    var leaderGeneralId: Long,
    var nationId: Long,
    var name: String,
    var meta: MutableMap<String, Any>,
    var createdAt: OffsetDateTime,
)

data class DiplomacySnapshot(
    val id: Long,
    val worldId: Long,
    var srcNationId: Long,
    var destNationId: Long,
    var stateCode: String,
    var term: Short,
    var isDead: Boolean,
    var isShowing: Boolean,
    var meta: MutableMap<String, Any>,
    var createdAt: OffsetDateTime,
)

data class GeneralTurnSnapshot(
    val id: Long,
    val worldId: Long,
    val generalId: Long,
    val turnIdx: Short,
    val actionCode: String,
    val arg: MutableMap<String, Any>,
    val brief: String?,
    val createdAt: OffsetDateTime,
)

data class NationTurnSnapshot(
    val id: Long,
    val worldId: Long,
    val nationId: Long,
    val officerLevel: Short,
    val turnIdx: Short,
    val actionCode: String,
    val arg: MutableMap<String, Any>,
    val brief: String?,
    val createdAt: OffsetDateTime,
)
