ALTER TABLE general ADD COLUMN dex_1 INTEGER NOT NULL DEFAULT 0;
ALTER TABLE general ADD COLUMN dex_2 INTEGER NOT NULL DEFAULT 0;
ALTER TABLE general ADD COLUMN dex_3 INTEGER NOT NULL DEFAULT 0;
ALTER TABLE general ADD COLUMN dex_4 INTEGER NOT NULL DEFAULT 0;
ALTER TABLE general ADD COLUMN dex_5 INTEGER NOT NULL DEFAULT 0;
ALTER TABLE general ADD COLUMN npc_org BIGINT;
ALTER TABLE general ADD COLUMN owner_name TEXT NOT NULL DEFAULT '';
ALTER TABLE general ADD COLUMN newmsg SMALLINT NOT NULL DEFAULT 0;

ALTER TABLE city ALTER COLUMN trust TYPE REAL USING trust::REAL;
ALTER TABLE city ALTER COLUMN dead TYPE INTEGER USING dead::INTEGER;
