"""arch_lint: each kind counts a planted violation (red probe) and leaves the clean shape alone; the CLI judges."""

from __future__ import annotations

import json
import subprocess
import sys
import tempfile
import textwrap
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import arch_lint  # noqa: E402

SCRIPT = Path(__file__).resolve().parent / "arch_lint.py"
KT = "src/main/kotlin/opensamguk"


def write(root: Path, rel: str, text: str) -> None:
    path = root / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(textwrap.dedent(text), encoding="utf-8")


def fixture(root: Path) -> None:
    write(root, "data/commands/input-catalog.json", json.dumps({"inputs": [{"inputId": i} for i in ("act.one", "act.two", "act.three")]}))
    # c1: two distinct inputIds in one file (violation) vs one (clean)
    write(root, f"logic/{KT}/logic/fam/TwoCommands.kt", 'package x\nval a = "act.one"\nval b = "act.two"\nval c = "act.two"\n')
    write(root, f"logic/{KT}/logic/fam/OneCommand.kt", 'package x\nval a = "act.three"\n')
    # c2: hub registrations
    write(root, f"app/game-engine/{KT}/engine/turn/ReservedTurnHandler.kt",
          'val m = mapOf("a" to InputHandler { }, "b" to InputHandler {\n})\n// InputHandler { in a comment does not count\n')
    write(root, f"app/game-engine/{KT}/engine/campaign/CourtHandler.kt", 'val m = mapOf("a" to InputHandler { })\n')
    # c3: wire variants
    write(root, f"common/{KT}/common/wire/TurnDaemonCommand.kt", """\
        sealed interface TurnDaemonCommand
        data class Move(
            val id: Int,
        ) : TurnDaemonCommand
        data object Stop : TurnDaemonCommand
        class Other : Unrelated
        """)
    # s1/s2: a long file with one long function; an expression body before it must not borrow its brace
    body = "\n".join(f"    val v{i} = {i}" for i in range(arch_lint.KOTLIN_FUN_P99 + 5))
    filler = "\n".join(f"// line {i}" for i in range(arch_lint.KOTLIN_FILE_P95))
    write(root, f"logic/{KT}/logic/fam/Long.kt", f"fun short(): Int = 1\nfun long() {{\n{body}\n}}\n{filler}\n")
    write(root, f"logic/{KT}/logic/fam/Generated.kt", "// GENERATED by tool\n" + filler + "\n")
    # d1: unused private
    write(root, f"logic/{KT}/logic/fam/Privates.kt", "private val unused = 1\nprivate fun used() = 2\nval x = used()\n")
    # web/game
    write(root, "web/game/lib/api.ts", "export const api = { get: () => fetch('/x') };\n")
    write(root, "web/game/lib/view.ts", "export const pure = 1;\nexport type Only = number;\n")
    write(root, "web/game/components/Raw.tsx", "export function Raw() { fetch('/y'); return null; }\n")
    write(root, "web/game/components/Screen.tsx", "import { api } from '@/lib/api';\nimport { pure } from '../lib/view';\nexport function Screen() { api.get(); return pure; }\n")
    write(root, "web/game/components/TypeOnly.tsx", "import type { Only } from '@/lib/api';\nimport { type X } from '@/lib/api';\nexport const T = 1;\n")
    write(root, "web/game/app/game/deep/page.tsx", "import { api } from '../../../lib/api';\nexport default function Page() { api.get(); return null; }\n")
    write(root, "web/game/lib/inputs.ts", "export const ids = ['act.one', \"act.two\"];\n")
    write(root, "web/game/lib/dead.ts", "export const DEAD = 1;\nexport const TESTED = 2;\nexport const SELF = 3;\nconst z = SELF;\n")
    write(root, "web/game/__tests__/dead.test.ts", "import { TESTED } from '@/lib/dead';\nTESTED;\n")
    # a test next to its component (components/x/__tests__/) is a test too: NEAR is test-only, not dead
    write(root, "web/game/lib/near.ts", "export const NEAR = 4;\n")
    write(root, "web/game/components/x/__tests__/near.test.ts", "import { NEAR } from '@/lib/near';\nNEAR;\n")
    # shared: an export used only by an app test is test-only
    write(root, "web/shared/src/onlyTested.ts", "export const ONLY_TESTED = 5;\n")
    write(root, "web/game/__tests__/shared.test.ts", "import { ONLY_TESTED } from '@opensamguk/ui';\nONLY_TESTED;\n")
    write(root, "web/game/app/game/uses/page.tsx",  # a framework entry that uses the planted components (they are not dead)
          "import { Raw } from '@/components/Raw';\nimport { Screen } from '@/components/Screen';\nimport { T } from '@/components/TypeOnly';\n"
          "import { U } from '@/components/UsesShared';\nimport { ids } from '@/lib/inputs';\nexport default function P() { return [Raw, Screen, T, U, ids]; }\n")
    write(root, "web/gateway/components/G.tsx", "export function G() { return null; }\n")
    write(root, "web/gateway/app/page.tsx", "import { G } from '@/components/G';\nexport default function P() { return G; }\n")
    write(root, "web/shared/src/index.ts", "export const shared = 1;\n")
    write(root, "web/game/components/UsesShared.tsx", "import { shared } from '@opensamguk/ui';\nexport const U = shared;\n")


class ArchLintScanTest(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = tempfile.TemporaryDirectory()
        self.root = Path(self.tmp.name)
        fixture(self.root)
        self.counts, self.findings = arch_lint.scan(self.root, {})

    def tearDown(self) -> None:
        self.tmp.cleanup()

    def test_backend_kinds_count_planted_violations(self) -> None:
        c = self.counts
        self.assertEqual(1, c["c1_multi_input_files"], self.findings["c1_multi_input_files"])
        self.assertEqual(2, c["c2_reserved_turn_handlers"])
        self.assertEqual(1, c["c2_court_handlers"])
        self.assertEqual(2, c["c3_wire_variants"])
        self.assertEqual(1, c["s1_kotlin_files_over_p95"], self.findings["s1_kotlin_files_over_p95"])  # generated file skipped
        self.assertEqual(1, c["s2_kotlin_funs_over_p99"], self.findings["s2_kotlin_funs_over_p99"])  # expression body skipped
        self.assertEqual(["logic/src/main/kotlin/opensamguk/logic/fam/Privates.kt unused"], self.findings["d1_kotlin_unused_private"])

    def test_frontend_kinds_count_planted_violations(self) -> None:
        c, f = self.counts, self.findings
        self.assertEqual(["web/game/components/Raw.tsx"], f["f1_raw_fetch_game"])
        self.assertEqual(sorted(["web/game/components/Screen.tsx", "web/game/app/game/deep/page.tsx"]),
                         sorted(f["f2_screen_api_game"]))  # type-only imports do not count; ../../../ resolves
        self.assertEqual(1, c["c1f_multi_input_game"])
        self.assertEqual(["web/game/lib/dead.ts DEAD"], f["d1f_unreferenced_game"])  # SELF is used in its own file
        self.assertNotIn("d1f_test_only_game", arch_lint.KINDS)
        self.assertEqual(0, c["d1f_unreferenced_shared"])  # consumed by web/game
        self.assertNotIn("d1f_test_only_shared", arch_lint.KINDS)

    def test_allowlist_exempts_a_path(self) -> None:
        counts, _ = arch_lint.scan(self.root, {"c1_multi_input_files": ["logic/src/main/kotlin/opensamguk/logic/fam/TwoCommands.kt"]})
        self.assertEqual(0, counts["c1_multi_input_files"])


class ArchLintCliTest(unittest.TestCase):
    def run_cli(self, root: Path, baseline: dict, *extra: str) -> subprocess.CompletedProcess:
        base = root / "baseline.json"
        base.write_text(json.dumps(baseline), encoding="utf-8")
        return subprocess.run([sys.executable, str(SCRIPT), "--root", str(root), "--baseline", str(base),
                               "--allowlist", str(root / "none.json"), *extra], capture_output=True, text=True)

    def test_ratchet_fails_above_baseline_and_report_only_does_not(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            fixture(root)
            counts, _ = arch_lint.scan(root, {})
            exact = {kind: counts[kind] for kind in arch_lint.KINDS}
            ok = self.run_cli(root, exact)
            self.assertEqual(0, ok.returncode, ok.stdout)
            self.assertIn("OK c1_multi_input_files: 1 <= baseline 1", ok.stdout)
            tighter = {**exact, "c1_multi_input_files": 0}
            red = self.run_cli(root, tighter)
            self.assertEqual(1, red.returncode, red.stdout)
            self.assertIn("FAIL c1_multi_input_files: 1 > baseline 0", red.stdout)
            self.assertIn("c1_multi_input_files examples: logic/src/main/kotlin/opensamguk/logic/fam/TwoCommands.kt 2", red.stdout)
            report = self.run_cli(root, tighter, "--report-only")
            self.assertEqual(0, report.returncode, report.stdout)
            self.assertIn("WOULD FAIL c1_multi_input_files", report.stdout)
            self.assertIn("despite WOULD FAIL", report.stdout)

    def test_base_ref_fails_a_new_violation_under_the_baseline_and_notes_new_exemptions(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            fixture(root)
            git = lambda *a: subprocess.run(["git", "-C", str(root), *a], check=True, capture_output=True)  # noqa: E731
            git("init", "-q")
            git("-c", "user.name=t", "-c", "user.email=t@t", "add", "-A")
            git("-c", "user.name=t", "-c", "user.email=t@t", "commit", "-qm", "base")
            loose = {kind: 999 for kind in arch_lint.KINDS}
            write(root, "web/game/components/Raw2.tsx", "export function Raw2() { fetch('/z'); return null; }\n")
            write(root, "tools/ci/arch_lint_allowlist.json", json.dumps({"exempt": {"c1_multi_input_files": [
                {"path": "logic/src/main/kotlin/opensamguk/logic/fam/TwoCommands.kt", "reason": "probe"}]}}))
            base = root / "baseline.json"
            base.write_text(json.dumps(loose), encoding="utf-8")
            run = subprocess.run([sys.executable, str(SCRIPT), "--root", str(root), "--repo", str(root), "--baseline", str(base),
                                  "--allowlist", str(root / "tools/ci/arch_lint_allowlist.json"), "--base-ref", "HEAD"],
                                 capture_output=True, text=True)
            self.assertEqual(1, run.returncode, run.stdout + run.stderr)
            self.assertIn("FAIL f1_raw_fetch_game: 2 > min(baseline 999, base 1)", run.stdout)
            self.assertIn("NOTE arch_lint_allowlist.json: 1 new exemption(s) vs base", run.stdout)

    def test_new_files_must_be_clean_renames_are_not_new_and_old_prs_get_a_note(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            fixture(root)
            git = lambda *a: subprocess.run(["git", "-C", str(root), "-c", "user.name=t", "-c", "user.email=t@t", *a],  # noqa: E731
                                            check=True, capture_output=True, text=True).stdout
            git("init", "-q")
            git("add", "-A")
            git("commit", "-qm", "base")
            # the rule turns on when its marker reaches the base (ratchet PR merge) — 2026-10-05T03:00Z here
            write(root, "tools/ci/arch_lint.py", f"NEW_FILE_RULE_MARKER = {arch_lint.NEW_FILE_RULE_MARKER!r}\n")
            git("add", "-A")
            subprocess.run(["git", "-C", str(root), "-c", "user.name=t", "-c", "user.email=t@t", "commit", "-qm", "ratchet"], check=True,
                           capture_output=True, env={**__import__("os").environ, "GIT_COMMITTER_DATE": "2026-10-05T03:00:00+00:00"})
            base = git("rev-parse", "HEAD").strip()
            git("mv", "web/game/components/Raw.tsx", "web/game/components/RawMoved.tsx")  # moved, not new
            write(root, "web/game/components/Raw2.tsx", "export function Raw2() { fetch('/z'); return null; }\n")
            git("add", "-A")
            git("commit", "-qm", "head")
            baseline = root / "baseline.json"
            baseline.write_text(json.dumps({kind: 999 for kind in arch_lint.KINDS}), encoding="utf-8")
            cli = [sys.executable, str(SCRIPT), "--root", str(root), "--repo", str(root), "--baseline", str(baseline),
                   "--allowlist", str(root / "none.json"), "--base-ref", base]
            run = subprocess.run(cli, capture_output=True, text=True)
            new_lines = [line for line in run.stdout.splitlines() if "new-file" in line]
            self.assertEqual(1, run.returncode, run.stdout)
            self.assertIn("FAIL new-file f1_raw_fetch_game: web/game/components/Raw2.tsx", new_lines)
            self.assertFalse([line for line in new_lines if "RawMoved" in line], new_lines)
            new_pr = subprocess.run([*cli, "--pr-created", "2026-10-05T03:00:01Z"], capture_output=True, text=True)
            self.assertIn("FAIL new-file f1_raw_fetch_game: web/game/components/Raw2.tsx", new_pr.stdout)
            old_pr = subprocess.run([*cli, "--pr-created", "2026-10-05T02:59:59Z"], capture_output=True, text=True)
            self.assertIn("NOTE new-file (PR opened before the rule took effect", old_pr.stdout)
            self.assertIn("f1_raw_fetch_game: web/game/components/Raw2.tsx", old_pr.stdout)
            self.assertNotIn("FAIL new-file", old_pr.stdout)


if __name__ == "__main__":
    unittest.main()
